In [8]:
import numpy as np   
  

# Matiz cuadrada
dim = 5


mResH = np.zeros(shape=(dim,dim))
mResV = np.zeros(shape=(dim,dim))
estado = True

#Este ciclo es para generar la matriz aleatoria "v" y que inere hasta que encuentre una en donde se encuntre una secuencia de nuemeros que cumple con el requisito buscado.

while estado == True: 
    
    v = np.random.randint(11, size=(dim , dim))#numero entre 0 - 10
    print(v) 

    #resta por filas por filas
    for i in range(5):#columnas
        for j in range(5):#filas
            if (i+1 < 5):
                mResH[i+1,j]=v[i+1,j] - v[i,j]
            else :
                break
            
    # print(f'Matriz de pasos por filas \n {mResH}')   
    
    ocurrenciaH = 0
    
    for i in range(5):#filas
        for j in range(5):#filas
            if (i+3 < 5) and ((mResH[i,j] == 0) or (mResH[i,j] == 1)) and (mResH[i+1,j] == 1) and (mResH[i+2,j] == 1) and (mResH[i+3,j] == 1):
                # print(f'{mResH[i,j]} , {mResH[i+1,j]} , {mResH[i+2,j]} , {mResH[i+3,j]}')
                ocurrenciaH += 1
                print(f'{ocurrenciaH} - Se encontro una secuencia en columna, desde [{i+1},{j+1}] hasta [{i+3+1},{j+1}]')
                estado = False
                break
                
            elif (i+4 < 5) and ((mResH[i+1,j] == 0) or (mResH[i+1,j] == 1)) and (mResH[i+2,j] == 1) and (mResH[i+3,j] == 1) and (mResH[i+4,j] == 1):
                # print(f'{mResH[i+1,j]} , {mResH[i+2,j]} , {mResH[i+3,j]} , {mResH[i+4,j]}')
                ocurrenciaH += 1
                print(f'{ocurrenciaH} - Se encontro una secuencia en columna, desde [{i+2},{j+1}] hasta [{i+4+1},{j+1}]')
                estado = False
                break
    

    for j in range(5):#filas
        for i in range(5):#columnas
            if (j+1 < 5):
                mResV[i,j+1]=v[i,j+1] - v[i,j]
            else :
                break   
            
    # print(f'Matriz de pasos por columnas \n {mResV}')
       
    ocurrenciaV = 0
              
    for i in range(5):#filas
        for j in range(5):#filas
            if (j+3 < 5) and ((mResV[i,j] == 0) or (mResV[i,j] == 1)) and (mResV[i,j+1] == 1) and (mResV[i,j+2] == 1) and (mResV[i,j+3] == 1):
                # print(f'{mResV[i,j]} , {mResV[i,j+1]} , {mResV[i,j+2]} , {mResV[i,j+3]}')
                ocurrenciaV += 1
                print(f'{ocurrenciaV} - Se encontro una secuencia en fila, desde [{i+1},{j+1}] hasta [{i+1},{j+3+1}]')
                estado = False
                break
                
            elif (j+4 < 5) and ((mResV[i,j+1] == 0) or (mResV[i,j+1] == 1)) and (mResV[i,j+2] == 1) and (mResV[i,j+3] == 1) and (mResV[i,j+4] == 1):
                # print(f'{mResV[i,j+1]} , {mResV[i,j+2]} , {mResV[i,j+3]} , {mResV[i,j+4]}')
                ocurrenciaV += 1
                print(f'{ocurrenciaV} - Se encontro una secuencia en fila, desde [{i+2},{j+1}] hasta [{i+5},{j+1}]')
                estado = False
                break


[[ 5  9  6  2  1]
 [ 7  3  4  8  0]
 [ 9  6  7  8  9]
 [10  5  6  7 10]
 [ 3  2  5  3 10]]
[[ 7  2  4  7  6]
 [ 2  3  6  7 10]
 [ 8  0  7  9  2]
 [ 2  9  7  2  0]
 [ 4  7  6  2  0]]
[[9 9 1 7 7]
 [2 0 8 9 2]
 [9 5 9 3 1]
 [2 4 5 8 1]
 [3 7 4 1 7]]
[[ 6  7  4  4 10]
 [ 5  0  7  7  8]
 [10  8  8  2  2]
 [ 0  1  7  5  1]
 [ 4  9  8  6  9]]
[[ 7  8  1  9  8]
 [ 0 10  4  3  1]
 [ 2  8  9  1  7]
 [ 6  0  0  0  0]
 [10  6  0  6  8]]
[[10  5  0  6  4]
 [ 1 10  5  7  9]
 [ 7  3  0  6  2]
 [ 5 10  7  5  6]
 [ 1  0  2  9  3]]
[[ 1  5  8  5  7]
 [ 7  4  4  6  8]
 [10  6  3  4  8]
 [ 8  9  5  7  6]
 [ 8  1  9 10  7]]
[[ 2 10  4 10  4]
 [ 6  8  8  3  4]
 [ 3  9  1  9  4]
 [10  3  8 10  8]
 [ 1  5 10  1  2]]
[[ 9  0 10  1  0]
 [ 9  9  9  9  3]
 [ 8 10  3  3  3]
 [ 3  3  1 10 10]
 [10  5  3  8  1]]
[[10  4  7 10  1]
 [10 10 10  6  9]
 [ 4  9  6  1  3]
 [ 6  9  6  3 10]
 [ 4  9  6  9  4]]
[[1 5 0 6 6]
 [9 4 5 0 8]
 [5 7 7 9 5]
 [2 7 6 5 3]
 [9 2 2 7 4]]
[[ 4  6  4  6  2]
 [10  5  5  0  2]
 [ 8  0  1  8